# Generated by Django 5.2.17 on 2026-10-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='session_id',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
    ]
