# Generated by Django 5.2.17 on 2026-10-06 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='parent',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'user_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('executive', 'Executive'), ('dealer', 'Dealer'), ('production', 'Production'), ('user_admin', 'User Admin'), ('parent_user', 'Parent User'), ('child_user', 'Child User')], db_index=True, default='child_user', max_length=20),
        ),
    ]
