# Generated by Django 5.2.17 on 2026-10-06 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_customuser_parent_customuser_user_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(blank=True, max_length=6, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('client_type', models.CharField(choices=[('dealer', 'Dealer'), ('direct', 'Direct')], db_index=True, default='direct', max_length=10)),
                ('authentication_status', models.CharField(choices=[('Pending', 'Pending'), ('Validating', 'Validating'), ('Approved', 'Approved'), ('Expired', 'Expired'), ('Blocked', 'Blocked')], db_index=True, default='Pending', max_length=25)),
                ('is_profile_active', models.BooleanField(default=False)),
                ('validity_from_date', models.DateField(blank=True, null=True)),
                ('validity_to_date', models.DateField(blank=True, null=True)),
                ('total_licence_unit', models.PositiveIntegerField(default=0)),
                ('total_user_count', models.PositiveIntegerField(default=0)),
                ('parent_user_count', models.PositiveIntegerField(default=0)),
                ('child_user_count', models.PositiveIntegerField(default=0)),
                ('total_device_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profiles', to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(blank=True, limit_choices_to={'role': 'dealer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_created_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'user_admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfiles',
                'db_table': 'userprofile',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client_type', 'authentication_status'], name='profile_client_auth_idx'), models.Index(fields=['dealer', 'authentication_status'], name='profile_dealer_auth_idx'), models.Index(fields=['validity_to_date'], name='profile_validity_idx')],
            },
        ),
    ]
