# Generated by Django 5.2.17 on 2026-10-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_id',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
